In [1]:
import numpy

In [2]:
r = numpy.array([
    [0.,1.,1.,0.,0.,1.,0.,1.,49.],
    [1.,0.,0.,0.,0.,1.,0.,1.,54.],
    [0.,0.,0.,1.,1.,1.,1.,1.,81.],
    [1.,   1.,   1.,   1.,   1.,   0.,   0.,   0.,   68.],
    [1.,   0.,   1.,   1.,   1.,   0.,   0.,   1.,   79.],
    [1.,   1.,   1.,   1.,   0.,   0.,   0.,   0.,   68.],
    [0.,   1.,   1.,   0.,   1.,   1.,   1.,   0.,   62.]
])
numpy.set_printoptions(linewidth=160)

In [3]:
r

array([[ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  1., 49.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  1., 54.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  1.,  1., 81.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0., 68.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  0.,  1., 79.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0., 68.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0., 62.]])

In [4]:
r[[0,1]] = r[[1,0]]
r

array([[ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  1., 54.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  1., 49.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  1.,  1., 81.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0., 68.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  0.,  1., 79.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0., 68.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0., 62.]])

In [5]:
r[3]-=r[0]
r[4]-=r[0]
r[5]-=r[0]
r

array([[ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  1., 54.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  1., 49.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  1.,  1., 81.],
       [ 0.,  1.,  1.,  1.,  1., -1.,  0., -1., 14.],
       [ 0.,  0.,  1.,  1.,  1., -1.,  0.,  0., 25.],
       [ 0.,  1.,  1.,  1.,  0., -1.,  0., -1., 14.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0., 62.]])

In [6]:
r[3]-=r[1]
r[5]-=r[1]
r[6]-=r[1]
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   0.,   1.,   1.,   1.,   1.,   1.,  81.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   0.,  -2.,   0.,  -2., -35.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   1.,  -1.,  13.]])

In [7]:
r[[2,4]] = r[[4,2]]
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [  0.,   0.,   0.,   1.,   1.,   1.,   1.,   1.,  81.],
       [  0.,   0.,   0.,   1.,   0.,  -2.,   0.,  -2., -35.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   1.,  -1.,  13.]])

In [8]:
r[4]-=r[3]
r[5]-=r[3]
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [  0.,   0.,   0.,   0.,   0.,   3.,   1.,   3., 116.],
       [  0.,   0.,   0.,   0.,  -1.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   1.,  -1.,  13.]])

In [9]:
r[[4,5]] = r[[5,4]]
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [  0.,   0.,   0.,   0.,  -1.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   3.,   1.,   3., 116.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   1.,  -1.,  13.]])

In [10]:
r[4] *= -1
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [ -0.,  -0.,  -0.,  -0.,   1.,  -0.,  -0.,  -0.,  -0.],
       [  0.,   0.,   0.,   0.,   0.,   3.,   1.,   3., 116.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   1.,  -1.,  13.]])

In [11]:
r[6]-=r[4]
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [ -0.,  -0.,  -0.,  -0.,   1.,  -0.,  -0.,  -0.,  -0.],
       [  0.,   0.,   0.,   0.,   0.,   3.,   1.,   3., 116.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   1.,  -1.,  13.]])

At this point, we have Row Echelon Form.  Is it possible to start seeking solutions at this point?

The bottom row has one free variable, which should make it easy to generate possible solutions (for that row).  Then try substituting into higher rows to solve for other variables.  But what if we encounter other free variables?

In [12]:
r[5]-=r[6]
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [ -0.,  -0.,  -0.,  -0.,   1.,  -0.,  -0.,  -0.,  -0.],
       [  0.,   0.,   0.,   0.,   0.,   3.,   0.,   4., 103.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   1.,  -1.,  13.]])

Because of the 3 in row r[5], I'm going to assume x[7] = 1 and x[6] = 14.  But this will cause a problem later, making x[1] = -10.  This will require x[7] to be larger.

In [13]:
r = numpy.vstack([r, numpy.array([0., 0., 0., 0., 0., 0., 0., 1., 13.])])
r

array([[  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,  54.],
       [  0.,   1.,   1.,   0.,   0.,   1.,   0.,   1.,  49.],
       [  0.,   0.,   1.,   1.,   1.,  -1.,   0.,   0.,  25.],
       [  0.,   0.,   0.,   1.,   1.,  -2.,   0.,  -2., -35.],
       [ -0.,  -0.,  -0.,  -0.,   1.,  -0.,  -0.,  -0.,  -0.],
       [  0.,   0.,   0.,   0.,   0.,   3.,   0.,   4., 103.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   1.,  -1.,  13.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,  13.]])

In [14]:
r[6] += r[7]
r[5] -= r[7]
r[3] += 2*r[7]
r[1] -= r[7]
r[0] -= r[7]
r

array([[ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 41.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  0., 36.],
       [ 0.,  0.,  1.,  1.,  1., -1.,  0.,  0., 25.],
       [ 0.,  0.,  0.,  1.,  1., -2.,  0.,  0., -9.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  3.,  0.,  3., 90.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 13.]])

In [15]:
r[5] /= 3.
r

array([[ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 41.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  0., 36.],
       [ 0.,  0.,  1.,  1.,  1., -1.,  0.,  0., 25.],
       [ 0.,  0.,  0.,  1.,  1., -2.,  0.,  0., -9.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  1., 30.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 13.]])

In [16]:
r[5] -= r[7]
r

array([[ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 41.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  0., 36.],
       [ 0.,  0.,  1.,  1.,  1., -1.,  0.,  0., 25.],
       [ 0.,  0.,  0.,  1.,  1., -2.,  0.,  0., -9.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 17.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 13.]])

In [17]:
r[0] -= r[5]
r[1] -= r[5]
r[2] += r[5]
r[3] += 2 * r[5]
r

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 24.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0., 19.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  0.,  0., 42.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  0., 25.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 17.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 13.]])

In [18]:
r[2] -= r[4]
r[3] -= r[4]
r

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 24.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0., 19.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  0.,  0., 42.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0., 25.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 17.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 13.]])

In [19]:
r[2] -= r[3]
r

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 24.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0., 19.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0., 17.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0., 25.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 17.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 13.]])

I was about to do `r[1] -= r[2]`, but that would leave a negative constant at `r[1][7]`, when x[7] was 1.  I looks like x[7] = 13 works.

In [20]:
r[1] -= r[2]
r

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 24.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0., 17.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0., 25.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 17.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 13.]])

In [21]:
x = r[:, 8]
x

array([24.,  2., 17., 25., -0., 17., 26., 13.])

In [22]:
x.sum()

np.float64(124.0)

In [23]:
assert(x[1]+x[2]+x[5]+x[7] == 49)
assert(x[0]+x[5]+x[7] == 54)
assert(x[3]+x[4]+x[5]+x[6]+x[7] == 81)
assert(x[0]+x[1]+x[2]+x[3]+x[4] == 68)
assert(x[0]+x[2]+x[3]+x[4]+x[7] == 79)
assert(x[0]+x[1]+x[2]+x[3] == 68)
assert(x[1]+x[2]+x[4]+x[5]+x[6] == 62)